; LoRa telemetry transmitter with sensors

[env:teensy41]
platform = teensy
board = teensy41
framework = arduino
monitor_speed = 115200
upload_port = COM5
monitor_port = COM5
lib_deps =
	adafruit/Adafruit Unified Sensor@^1.1.15
	adafruit/Adafruit BMP5xx Library@^1.0.2
	adafruit/Adafruit LIS2MDL@^2.1.8
	bolderflight/Bolder Flight Systems BMI088@^1.0.1
	sandeepmistry/LoRa@^0.8.0
